export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';

export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const REMOVE_MESSAGE_SUCCESS = 'REMOVE_MESSAGE_SUCCESS';
export const REMOVE_MESSAGE_ERROR = 'REMOVE_MESSAGE_ERROR';

export const LOAD_MESSAGES_PENDING = 'LOAD_MESSAGES_PENDING';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_ERROR = 'LOAD_MESSAGES_ERROR';