// MESSAGES
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

export const LOAD_MESSAGES_PENDING = 'LOAD_MESSAGES_PENDING';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_ERROR = 'LOAD_MESSAGES_ERROR';

// USERS
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';